#!/bin/sh
#
# Wait for entropy.

set -e

PATH=/proc/sys/kernel/random/entropy_avail
ENTROPY="0"
THRESHOLD="512"

get () {
	ENTROPY=$(/bin/cat $PATH)
}

while true; do
	get
	if [ "$ENTROPY" -gt "$THRESHOLD" ]; then
		break
	fi
	echo "Waiting for entropy: $ENTROPY bytes"
	/bin/sleep 1
done

echo "Entropy is available: $ENTROPY bytes"
