#!/bin/sh

set -e

case "$1" in
    configure|triggered)
        if [ -e "/etc/watchdog.conf" ]; then
            sed -i "s/^#watchdog\-device.*/watchdog-device\t= \/dev\/watchdog/g" /etc/watchdog.conf
            sed -i "s/^watchdog\-device\t=.*/watchdog-device\t= \/dev\/watchdog/g" /etc/watchdog.conf
        fi
        if [ -e "/etc/init/watchdog.conf" ]; then
            service watchdog restart || true
        fi
        ;;
    *)
        exit 0
    ;;
esac

#DEBHELPER#
