#!/bin/bash

# Generate random keys for Spreed WebRTC.
sed -i "s|sessionSecret = .*|sessionSecret = $(libressl-openssl rand -hex 32)|" /etc/spreed/webrtc.conf
sed -i "s|encryptionSecret = .*|encryptionSecret = $(libressl-openssl rand -hex 24)|" /etc/spreed/webrtc.conf
sed -i "s|serverToken = .*|serverToken = $(libressl-openssl rand -hex 16)|" /etc/spreed/webrtc.conf

# Restart service.
invoke-rc.d spreed-webrtc restart

