#!/bin/bash

# Generate random keys for Spreed WebRTC.
sed -i "s|sessionSecret = .*|sessionSecret = \$(xxd -ps -l 32 -c 32 /dev/random)|" /etc/spreed/webrtc.conf
sed -i "s|encryptionSecret = .*|encryptionSecret = \$(xxd -ps -l 16 -c 16 /dev/random)|" /etc/spreed/webrtc.conf
sed -i "s|serverToken = .*|serverToken = \$(xxd -ps -l 16 -c 16 /dev/random)|" /etc/spreed/webrtc.conf

# Restart service.
invoke-rc.d spreed-webrtc restart

